AWSTemplateFormatVersion: 2010-09-09

# This template require macros.yml to be deployed first

Parameters:
  stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  VPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.100.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value:  "vpc-${stage}"
  VPC2:
    Type: AWS::EC2::VPC
    Properties:
      Fn::Transform: PropertyAdder
      CidrBlock: 10.200.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

Transform:
  - StringSubstitution