version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/webapp-0.0.1-SNAPSHOT.jar webapp-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - webapp-0.0.1-SNAPSHOT.war