AWSTemplateFormatVersion: 2010-09-09

# Create vpc with private & public subnet and one EC2 in each subnet

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-template-bucket.s3.amazonaws.com/vpc-bastion.yml
  Ec2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-template-bucket.s3.amazonaws.com/ec2-bastion.yml

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VpcStack.Outputs.PrivateRTId
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIPAddress.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC-B-NAT-GW
  ElasticIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !GetAtt VpcStack.Outputs.VpcId
