AWSTemplateFormatVersion: 2010-09-09

#  For REST API after each change of template you have to redeploy it manually from console. Create rest api + body/header/querystring validation + cors + lambda integration.
#  Static values should be enclosed in both double & single quotes: "'static_value'"
#  VALIDATION: curl -H 'Content-type: application/json' -H 'user-id: 1' --data '{"name":"jack","age":30}' {API_URL}/?status=1
#  If you omit header/querystring you got exception: {"message": "Missing required request parameters: [user-id, status]"}. You can also require path variable to be present like `"method.request.path.profile_id": true`, but this is redundant cause if this is your path you can't call method without it
#  If body validation failed, you got exception: {"message": "Invalid request body"}. Yet body validation depends on `Content-type` header. So if you pass not `application/json`, you don't get this error.
#  TRANSFORMATION:  {"message": "Unsupported Media Type"}
#  CORS: `curl -v -X OPTIONS -H 'Origin: http://site.io' -H 'Access-Control-Request-Method: PUT' {API_URL}`. You can change site to my.com, it would also work, yet other sites wouldn't (request would return 200, but no cors headers)

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-LambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
  LogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-LogPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogStreams"
            Resource: "*"
      Roles:
        - !Ref LambdaRole
  InfoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Show basic information about app
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = (params, context, cb) => {
              cb(null, {
                statusCode: 200,
                body: JSON.stringify({"msg": "Welcome to REST API", params}),
                headers: {"Content-Type": "application/json"}
              });
          }
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Info
  ApiGatewayLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt InfoLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join [ "", ["arn:aws:execute-api:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", !Ref RestApi, "/*/*/*"]]

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Cors example using REST API
      Name: REST API CORS
      EndpointConfiguration:
        Types:
          - REGIONAL
  BaseMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !GetAtt RestApi.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      RequestValidatorId: !Ref PersonRequestValidator
      RequestParameters:
        "method.request.header.user-id": true
        "method.request.querystring.status": true
      RequestModels:
        application/json: PersonModel
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InfoLambda.Arn}/invocations
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: "#set ($root=$input.path('$')) { \"stage\": \"$root.name\", \"user-id\": \"$root.age\" }"
        RequestParameters:
          "integration.request.header.profile-id": "'123'"
          "integration.request.querystring.state": "'done'"
  PersonRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: PersonRequestValidator
      RestApiId: !Ref RestApi
      ValidateRequestBody: true
      ValidateRequestParameters: true
  PersonModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref RestApi
      ContentType: application/json
      Description: Model of Person
      Name: PersonModel
      Schema:
        "$schema": "http://json-schema.org/draft-04/schema#"
        title: UserModel
        type: object
        required:
          - name
          - age
        properties:
          name:
            type: string
          age:
            type: integer

  CorsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: cors
  CorsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref CorsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET, POST, PUT, DELETE, OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'http://site.io'"
              method.response.header.Access-Control-Allow-Headers: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: '{"statusCode": 200}'
  Deployment:
    DependsOn:
      - BaseMethod
      - CorsMethod
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      Description: My deployment
  DevStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: dev
      Description: Dev Stage
      RestApiId: !Ref RestApi
      DeploymentId: !Ref Deployment