AWSTemplateFormatVersion: 2010-09-09

# Create dev/prod ec2 based on input param

Parameters:
  Env:
    Description: Environment type.
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: env should be dev or prod.

Conditions:
  Prod: !Equals [ !Ref Env, prod ]
  Dev: !Equals [ !Ref Env, dev ]

Resources:
  DevEC2:
    Condition: Dev
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d95fab7fff3776c
      KeyName: mykey
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2-${Env}

  ProdC2:
    Condition: Prod
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d95fab7fff3776c
      KeyName: mykey
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2-${Env}