AWSTemplateFormatVersion: 2010-09-09

#

Resources:
  Policy:
    Version: 2012-10-17
    Statement:
      - Effect: Allow
        Principal:
          AWS: arn:aws:iam::{ACCOUNT_B}:user/accountBusername
        Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
        Resource:
          - arn:aws:s3:::AccountABucketName/*

#  ELB:
#    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
#    Properties:
#      Scheme: internet-facing
#      Type: application
#      SecurityGroups:
#        - !GetAtt ElbSG.GroupId
#      Subnets:
#        - !Ref PublicSubnet1
#        - !Ref PublicSubnet2
#      Tags:
#        - Key: Name
#          Value: !Sub ${AWS::StackName}-MyVpc-ELB
#  TG:
#    Type: AWS::ElasticLoadBalancingV2::TargetGroup
#    Properties:
#      VpcId: !Ref VPC
#      TargetType: instance
#      Port: 80
#      Protocol: HTTP
#      Targets:
#        - Id: !Ref PublicInstance1
#        - Id: !Ref PublicInstance2
#      Tags:
#        - Key: Name
#          Value: !Sub ${AWS::StackName}-MyVpc-TG
#  HttpListener:
#    Type: AWS::ElasticLoadBalancingV2::Listener
#    Properties:
#      DefaultActions:
#        - Type: fixed-response
#          FixedResponseConfig:
#            StatusCode: 403
#      LoadBalancerArn: !Ref ELB
#      Port: 80
#      Protocol: HTTP
#  HttpRule:
#    Type: AWS::ElasticLoadBalancingV2::ListenerRule
#    Properties:
#      Priority: 10
#      Actions:
#        - Type: forward
#          TargetGroupArn: !Ref TG
#      Conditions:
#        - Field: path-pattern
#          PathPatternConfig:
#            Values:
#              - "/"
#              - "/index.html"
#              - "/public.html"
#      ListenerArn: !Ref HttpListener