AWSTemplateFormatVersion: 2010-09-09

# TODO: fix error => Stack set operation was unexpectedly stopped or failed

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.100.0.0/16

  MyStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Sub ${AWS::StackName}-MyStackSet
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - Regions:
            - us-east-1
          DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
      TemplateBody: |
        Resources:
          VPC:
            Type: AWS::EC2::VPC
            Properties:
              CidrBlock: 10.200.0.0/16
